### ISSUE TITLE
Status and roadmap for google-maps-ios-utils

### ISSUE THREAD

**Issue by wangela** [googlemaps/google-maps-ios-utils#473]
This issue describes the current status and roadmap for the Google Maps SDK for iOS Utility Library. I will edit this top comment as progress is made or plans change.

It's been 4 months since my [last comment](https://github.com/googlemaps/google-maps-ios-utils/issues/458#issuecomment-1998082436) describing the work that needed to be done, and we're all frustrated that a new version hasn't been released yet. Communication has been sparse because it's been hard to predict when the final issues would be resolved, since these are problems we haven't encountered before across my own team, consults with teams that manage other Google products for iOS developers, and (based on my searching on the web) many other Swift package and CocoaPods pod owners. Even documenting the goals for the next 2-3 releases here has been challenging as I've discovered new obstacles and solutions on a daily basis. 

### Design Considerations

Updating the Maps iOS Utils library to support Maps SDK for iOS v8 has been painful due to several factors:

<table>
  <tr>
   <td><strong>Challenge</strong>
   </td>
   <td><strong>Plan</strong>
   </td>
  </tr>
  <tr>
   <td>The library's build and release workflows are based on Carthage generating an XCFramework, which <a href="https://developers.google.com/maps/documentation/ios-sdk/release-notes#2022-06-27">stopped being compatible</a> with the Maps SDK for iOS since v7.
   </td>
   <td rowspan="2">Build from source instead of using Carthage to generate an XCFramework and publishing a binary dependency. The pros and cons of binary vs multi-target Swift packages are weighed in this <a href="https://pspdfkit.com/blog/2023/developing-mixed-source-swift-packages/">blog post</a>.
   </td>
  </tr>
  <tr>
   <td>Apple <a href="https://developer.apple.com/documentation/xcode/identifying-binary-dependencies">recommends</a> depending on Swift packages built from source rather than binary dependencies.
   </td>
  </tr>
  <tr>
   <td>Apple's <a href="https://developer.apple.com/documentation/xcode/creating-a-standalone-swift-package-with-xcode">build workflow for Swift packages</a> has changed significantly since the original build workflows were written. We previously relied on Xcode Schemes to build and test the package and companion app.
   </td>
   <td>Validate building and testing the package using <a href="https://forums.swift.org/t/swiftpm-swift-build-for-ios/42517/5">recommended workflow</a> for building and testing Swift packages targeting iOS (using `xcodebuild`) for building and testing Swift packages. The workflows will run on the GitHub Runnner selected by <a href="https://github.com/actions/runner-images/tree/main">`macos-latest`</a> until the latest encounters build errors.
   </td>
  </tr>
  <tr>
   <td>Swift Package Manager built from source does not support mixed language targets (<a href="https://forums.swift.org/t/se-0403-package-manager-mixed-language-target-support/66202">current proposal in Swift Evolution</a>), so this library (with Objective-C code and Swift code) requires an <a href="https://github.com/swiftlang/swift-package-manager/blob/main/Documentation/Usage.md#creating-c-language-targets">Objective-C target</a> and a Swift target.
   </td>
   <td rowspan="3"><p>Near-term: Use the undocumented @exported feature to import the Objective-C target to the Swift target. CocoaPods does not require this because CocoaPods supports mixed-language targets. This <a href="https://joesusnick.medium.com/swift-package-manager-with-a-mixed-swift-and-objective-c-project-part-2-2-e71dad234e6">blog post</a> describes one developer's journey and learnings from attempting it.</p>
 <p>Tests can be shared by both Swift Package and CocoaPods build and test workflows.</p>
<p>Mid-term: Translate all source code and tests from Obj-C to Swift so the package is pure Swift and we only need one target that can be used for both SPM and CocoaPods.</p>
   </td>
  </tr>
  <tr>
   <td>Publishing to CocoaPods <a href="https://guides.cocoapods.org/making/using-pod-lib-create.html#deploying-your-library">requires</a> <a href="https://guides.cocoapods.org/making/using-pod-lib-create.html#deploying-your-library">passing</a> `pod lib lint` (local only validation) and `pod spec lint` (local+network validation) which is based on installing the library based on the Podspec.
<p>
This runs a test target specified in the Podspec; as long as the import signatures for projects built with SPM vs CocoaPods are the same, these tests can be shared.
   </td>
  </tr>
  <tr>
   <td>Unit testing in Objective-C requires mock Google Maps objects, but OCMock support for Swift Package Manager is <a href="https://github.com/erikdoe/ocmock/issues/500">incomplete</a>.
   </td>
  </tr>
  <tr>
   <td>Unit testing in Swift requires mock Google Maps objects, but there is <a href="https://stackoverflow.com/questions/24174130/mocking-in-swift">no equivalent</a> to OCMock for Swift.
   </td>
   <td>Complete the Swift-based mock work in progress when we translate the Objective-C tests to Swift.
   </td>
  </tr>
</table>

### Roadmap for google-maps-ios-utils:

**v5.0 (July)**

We have the Swift package build succeeding and passing tests and the CocoaPods build succeeding with one remaining set of errors to resolve related to making the resource files available to Swift tests in the podspec.

- [ ] Support Maps SDK v8
- [ ] Support installation of the utility library via Swift Package Manager in Xcode
- [ ] Support for installation of the utility library via CocoaPods
- [ ] End support for installation of the utility library via Carthage
- [ ] Build SPM and CocoaPod from source (GitHub) instead of shipping SPM as a binary (XCFramework)
- [ ] Update [build, test, and release action workflows](https://github.com/googlemaps/google-maps-ios-utils/actions) to use the latest methods to validate the library upon every pull request and merge to main.
  - [ ] Unit tests pass via both xcodebuild test and pod lib lint
  - [ ] Remove the side-by-side app as a build validator
  - [ ] Build the Podfile-based Objective-C sample app and Swift sample app as validation of CocoaPods-based build
- [ ] Maintain Code Coverage and Dependabot action workflows (no regressions)
- [ ] Implement correct OS version minimums to ensure library compatibility with major version releases of the Maps SDK for iOS.
- [ ] Update the README with the new installation recommendations.

**v6.0 (July)**

- [ ] Support Maps SDK v9

**v7.0 (September)**

- [ ] Convert source code from a mix of Objective-C and Swift to all Swift so the library can have a single target
- [ ] Convert Objective-C unit tests to Swift unit tests so that all tests are Swift

**Comment by Rexios80** [comment]
@wangela please pin this issue

**Comment by alexookah** [comment]
So we wont be able to update to V9 google maps until google maps utils has done all these things mentioned in the roadmap and get to version 6.
Have I understood correct? 
Has anyone successfully updated to google maps v9 with the current state of google maps utils (branch: `wangela/8-0-0`?

**Comment by wangela** [comment]
🚀 v5.0.0 (supporting Maps SDK v8, minimum iOS 14) and v6.0.0 (supporting Maps SDK v9, minimum iOS 15) of the Maps SDK for iOS Utility Library are now available via SPM and CocoaPods.

See the [Installation](https://github.com/googlemaps/google-maps-ios-utils?tab=readme-ov-file#installation) section of the README for guidance on how to install the version of your choice.

@alexookah With all the work that went into v5.0.0, our updates to this library should be much faster. It took less than a day to cut v6.0.0.

@ThePragmaticArt This library has supported SPM since 2020 but the SDK didn't support SPM until December last year. Every engineering team has to make difficult choices between modernization and feature development. For this library, the modernization debt we've held by relying on Carthage and a mixed-language codebase proved to be very painful. For our closed-source SDKs, [public Issue Tracker](https://developers.google.com/maps/documentation/ios-sdk/support#issue-tracker) is the best way to tell us what you want us to prioritize. For example, the [upvotes on the IssueTracker issue](https://issuetracker.google.com/issues/141721633) requesting SPM support helped build the case for prioritizing that release modernization work. Similarly on another Apple-related modernization effort, we're looking for evidence that developers want full support for Google Maps in SwiftUI but we're not seeing many issues or upvotes raised about that yet.

Regarding CocoaPods, we still see CocoaPods being the channel of choice for many developers, and currently it's the only way of loading libraries for Flutter.

With our plan to translate this library to 100% Swift source next, we'll hopefully be able to return to developer experience improvements and feature development. I've added guidance to the [initial comment](#issue-2431084157) on how to help us prioritize our feature roadmap.

**Comment by Rexios80** [comment]
@wangela Thank you so much for this! I will start implementing this in `google_maps_flutter_ios` right now.

**Comment by Rexios80** [comment]
We just landed the iOS heatmaps implementation thanks to this
- https://github.com/flutter/packages/pull/7314

And marker clustering is about to land soon
- https://github.com/flutter/packages/pull/6186

Thank you again for the work on this @wangela!

**Comment by wojmangh** [comment]
I'm migrating a big app to Tuist, where we want to use dynamic frameworks. There was a problem with this lib, so I'm trying `swift-main`. We will test if it works as expected but from purely API changes, this is my feedback.

- `'GMUClusterManager.clearItems' is inaccessible due to 'internal' protection level` - we were using it

- `Type 'StoresClusterIconGenerator' does not conform to protocol 'GMUClusterIconGenerator'` icon(forSize..) -> iconForSize() - is the necessary?
